name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests_linux:
    name: "Tests: Node ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20", "22"]

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2.2.3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - run: pnpm test

  build:
    name: "Build"
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2.2.3
      - run: pnpm install
      - run: pnpm build

  tests_ts:
    name: "Tests: TS ${{ matrix.ts-version }}"
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        ts-version: ["5.3", "5.4", "5.5", "5.6", "5.7", "5.8", "next"]

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2.2.3
      - run: pnpm install
      - run: pnpm add --save-dev typescript@${{ matrix.ts-version }}
      - run: pnpm type-check
