name: Nightly TypeScript Run

jobs:
  ts-next:
    name: typescript@next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2.2.3
      - run: pnpm install
      - run: pnpm add --save-dev typescript@next
      - run: pnpm type-check

# ...nightly at midnight
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
